version: "3"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: go-users
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go-users
      MYSQL_INITDB_SKIP_TZINFO: "true"
    volumes:
      - ./ddl:/docker-entrypoint-initdb.d:ro
